config=pd.read_csv(self.path,sep=',',error_bad_lines=False,warn_bad_lines=False)
TypeError: read_csv() got an unexpected keyword argument 'error_bad_lines'
init block has exception
